# Generated by Django 2.1.7 on 2019-04-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_cart_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_sale',
            field=models.BooleanField(default=True),
        ),
    ]
