# Generated by Django 2.1.7 on 2019-04-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190405_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price_before_sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
