# Generated by Django 2.1.7 on 2019-04-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCharacteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total_usage_of_coupons', models.PositiveIntegerField(default=0)),
                ('total_count_of_products', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
