# Generated by Django 2.1.7 on 2019-04-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20190406_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopCharacteristics',
        ),
    ]
