# Generated by Django 2.1.7 on 2019-04-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_delete_shopcharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
