# Generated by Django 2.1.7 on 2019-04-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_shopcharacteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcharacteristic',
            name='save_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
