# Generated by Django 2.1.7 on 2019-04-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_shopcharacteristic_save_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcharacteristic',
            name='total_usage_of_coupons',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
