# Generated by Django 2.1.7 on 2019-04-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
